prompt --application/set_environment
set define off verify off feedback off
whenever sqlerror exit sql.sqlcode rollback
--------------------------------------------------------------------------------
--
-- Oracle APEX export file
--
-- You should run this script using a SQL client connected to the database as
-- the owner (parsing schema) of the application or as a database user with the
-- APEX_ADMINISTRATOR_ROLE role.
--
-- This export file has been automatically generated. Modifying this file is not
-- supported by Oracle and can lead to unexpected application and/or instance
-- behavior now or in the future.
--
-- NOTE: Calls to apex_application_install override the defaults below.
--
--------------------------------------------------------------------------------
begin
wwv_flow_imp.import_begin (
 p_version_yyyy_mm_dd=>'2024.11.30'
,p_release=>'24.2.0'
,p_default_workspace_id=>100000
,p_default_application_id=>135
,p_default_id_offset=>0
,p_default_owner=>'UNORGANIZED'
);
end;
/
 
prompt APPLICATION 135 - Playground
--
-- Application Export:
--   Application:     135
--   Name:            Playground
--   Exported By:     MESBAHWORLD
--   Flashback:       0
--   Export Type:     Page Export
--   Manifest
--     PAGE: 6
--   Manifest End
--   Version:         24.2.0
--   Instance ID:     743399910586821
--

begin
null;
end;
/
prompt --application/pages/delete_00006
begin
wwv_flow_imp_page.remove_page (p_flow_id=>wwv_flow.g_flow_id, p_page_id=>6);
end;
/
prompt --application/pages/page_00006
begin
wwv_flow_imp_page.create_page(
 p_id=>6
,p_name=>'PG1_Landing Page'
,p_alias=>'PG1-LANDING-PAGE'
,p_step_title=>'PG1_Landing Page'
,p_autocomplete_on_off=>'OFF'
,p_html_page_header=>wwv_flow_string.join(wwv_flow_t_varchar2(
'<meta charset="UTF-8">',
'<meta name="viewport" content="width=device-width, initial-scale=1.0">',
'<title>Employee Management Module</title>',
''))
,p_javascript_file_urls=>wwv_flow_string.join(wwv_flow_t_varchar2(
'/* Prism.js JS  */',
'https://cdnjs.cloudflare.com/ajax/libs/prism/1.29.0/prism.min.js',
'https://cdnjs.cloudflare.com/ajax/libs/prism/1.29.0/components/prism-sql.min.js',
'https://cdnjs.cloudflare.com/ajax/libs/prism/1.29.0/components/prism-javascript.min.js',
'',
''))
,p_javascript_code_onload=>wwv_flow_string.join(wwv_flow_t_varchar2(
'  // Resume Modal',
'  const resumeBtn = document.getElementById(''resumeBtn'');',
'  const modal = document.getElementById(''resumeModal'');',
'  const closeModal = document.getElementById(''closeModal'');',
'  const empSearch = document.getElementById(''empSearch'');',
'  const searchResults = document.getElementById(''searchResults'');',
'',
'  resumeBtn.addEventListener(''click'', () => {',
'    modal.style.display = ''flex'';',
'    empSearch.value = '''';',
'    searchResults.innerHTML = '''';',
'    empSearch.focus();',
'  });',
'  closeModal.addEventListener(''click'', () => { modal.style.display = ''none''; });',
'  window.addEventListener(''click'', e => { if(e.target===modal) modal.style.display=''none''; });',
'',
'  let debounceTimer;',
'  empSearch.addEventListener(''input'', () => {',
'    clearTimeout(debounceTimer);',
'    debounceTimer = setTimeout(fetchEmployees, 300);',
'  });',
'',
'  async function fetchEmployees(){',
'    const query = empSearch.value.trim();',
'    if(!query){ searchResults.innerHTML=''''; return; }',
'',
'    let url = !isNaN(query) ? ',
'      `https://mesbahuddin.com/web/unorg/pg1_emp_man/list_emp?id=${query}` :',
'      `https://mesbahuddin.com/web/unorg/pg1_emp_man/list_emp?p_emp_name=${encodeURIComponent(query)}`;',
'',
'    try{',
'      const res = await fetch(url);',
'      const data = await res.json();',
'      if(data.status===''success'' && data.data.length>0){',
'        searchResults.innerHTML = data.data.map(emp => ',
'          `<div data-id="${emp.empId}">${emp.fullName} (ID: ${emp.empId})</div>`',
'        ).join('''');',
'      } else {',
'        searchResults.innerHTML = ''<div>No employee found</div>'';',
'      }',
'    }catch(err){',
'      searchResults.innerHTML = ''<div>Error fetching data</div>'';',
'      console.error(''Fetch error'', err);',
'    }',
'  }',
'',
'  searchResults.addEventListener(''click'', e=>{',
'    const empId = e.target.getAttribute(''data-id'');',
'    if(empId){',
'      window.open(`https://mesbahuddin.com/web/r/apps/playground/resume?p3_emp_id=${empId}`, ''_blank'');',
'      modal.style.display=''none'';',
'    }',
'  });',
'',
'  // Populate Documentation Sidebar dynamically',
'  const sidebar = document.getElementById(''docSidebar'');',
'  const docCards = document.querySelectorAll(''.doc-card'');',
'  docCards.forEach(card => {',
'    const title = card.querySelector(''h3'').innerText;',
'    const id = card.id;',
'    const link = document.createElement(''a'');',
'    link.href = `#${id}`;',
'    link.innerText = title;',
'    sidebar.appendChild(link);',
'  });',
''))
,p_css_file_urls=>wwv_flow_string.join(wwv_flow_t_varchar2(
'/*  Prism.js CSS  */',
'https://cdnjs.cloudflare.com/ajax/libs/prism/1.29.0/themes/prism-tomorrow.min.css',
''))
,p_inline_css=>wwv_flow_string.join(wwv_flow_t_varchar2(
'        :root {',
'            --secondary-color: #333;',
'            --light-gray: #f5f5f5;',
'            --border-color: #ddd;',
'            --shadow: 0 4px 6px rgba(0, 0, 0, 0.1);',
'            --transition: all 0.3s ease;',
'        }',
'        ',
'        .t-Footer, .t-Header  {',
'            display: none !important;',
'        }',
'',
'/* ------------------------------------------------------------------------------------------ */',
'',
':root {',
'  --primary-color: #FFD700;',
'  --text-dark: #333;',
'  --bg-light: #f9f9f9;',
'}',
'body {',
'  font-family: Arial, sans-serif;',
'  margin: 0;',
'  background: var(--bg-light);',
'  color: var(--text-dark);',
'}',
'header {',
'  background: var(--primary-color);',
'  padding: 1rem 2rem;',
'  text-align: center;',
'  font-size: 1.5rem;',
'  font-weight: bold;',
'}',
'/* Two column layout */',
'.main-wrapper {',
'  display: flex;',
'  gap: 2rem;',
'  padding: 2rem;',
'}',
'',
'/* Left Column */',
'.left-column {',
'  flex: 1;',
'  max-width: calc(100% - 350px); /* Leaves room for right sidebar */',
'}',
'',
'/* Right Column (Sidebar) */',
'.right-column {',
'  width: 300px; /* fixed width */',
'  max-width: 350px; /* optional max */',
'  position: sticky;',
'  top: 100px;',
'  height: fit-content;',
'}',
'/* Top cards layout */',
'.top-cards {',
'  display: grid;',
'  grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));',
'  gap: 1.5rem;',
'  margin-bottom: 2rem;',
'}',
'',
'/* Cards */',
'.card {',
'  background: white;',
'  padding: 1.5rem;',
'  border-radius: 12px;',
'  box-shadow: 0 4px 10px rgba(0,0,0,0.1);',
'  text-align: center;',
'  transition: transform 0.2s;',
'  margin-bottom: 1.5rem;',
'}',
'.card:hover { transform: translateY(-5px); }',
'.card h2 { margin: 1rem 0; font-size: 1.3rem; }',
'.btn {',
'  display: inline-block;',
'  background: var(--primary-color);',
'  color: black;',
'  padding: 0.6rem 1.2rem;',
'  border-radius: 8px;',
'  font-weight: bold;',
'  text-decoration: none;',
'  cursor: pointer;',
'}',
'.btn:hover { background: #e6c200; }',
'',
'/* Modal for Resume Search */',
'.modal {',
'  display: none;',
'  position: fixed;',
'  z-index: 999;',
'  left: 0; top: 0;',
'  width: 100%; height: 100%;',
'  background-color: rgba(0,0,0,0.5);',
'  justify-content: center;',
'  align-items: center;',
'}',
'.modal-content {',
'  background: white;',
'  padding: 2rem;',
'  border-radius: 12px;',
'  width: 90%;',
'  max-width: 400px;',
'  text-align: center;',
'  position: relative;',
'}',
'.modal input {',
'  width: 80%;',
'  padding: 0.5rem;',
'  margin: 1rem 0;',
'  border-radius: 6px;',
'  border: 1px solid #ccc;',
'}',
'.close-btn {',
'  position: absolute;',
'  top: 10px; right: 20px;',
'  font-size: 1.5rem;',
'  font-weight: bold;',
'  cursor: pointer;',
'}',
'.search-result {',
'  margin-top: 1rem;',
'  text-align: left;',
'  max-height: 150px;',
'  overflow-y: auto;',
'}',
'.search-result div {',
'  padding: 0.5rem;',
'  border-bottom: 1px solid #ddd;',
'  cursor: pointer;',
'}',
'.search-result div:hover {',
'  background: #f1f1f1;',
'}',
'',
'/* Documentation Section */',
'.docs-section {',
'  margin-top: 2rem;',
'}',
'.doc-card {',
'  background: white;',
'  padding: 1.5rem;',
'  border-radius: 12px;',
'  box-shadow: 0 4px 10px rgba(0,0,0,0.1);',
'  margin-bottom: 1.5rem;',
'  position: relative;',
'}',
'.doc-card h3 {',
'  margin: 0 0 0.5rem 0;',
'  color: var(--primary-color);',
'}',
'.doc-card a.doc-id-link {',
'  position: absolute;',
'  top: 1rem;',
'  right: 1rem;',
'  font-size: 14px;',
'  text-decoration: none;',
'  color: var(--primary-color);',
'}',
'.doc-card a.doc-id-link:hover { text-decoration: underline; }',
'.doc-card p { margin: 0.5rem 0; }',
'.doc-tag {',
'  display: inline-block;',
'  background: #eee;',
'  color: #333;',
'  padding: 0.2rem 0.5rem;',
'  border-radius: 6px;',
'  margin-right: 0.5rem;',
'  font-size: 12px;',
'}',
'.doc-links a {',
'  display: inline-block;',
'  margin: 0.3rem 0.5rem 0.3rem 0;',
'  text-decoration: none;',
'  color: var(--primary-color);',
'  font-weight: bold;',
'}',
'.doc-links a:hover { text-decoration: underline; }',
'pre {',
'  background: #2d2d2d;',
'  color: #f8f8f2;',
'  padding: 1rem;',
'  border-radius: 8px;',
'  overflow-x: auto;',
'}',
'',
'/* Sidebar */',
'.doc-sidebar {',
'  background: white;',
'  border-radius: 12px;',
'  box-shadow: 0 4px 10px rgba(0,0,0,0.1);',
'  padding: 1rem;',
'}',
'.doc-sidebar h4 { margin-top: 0; font-size: 1rem; color: var(--primary-color); }',
'.doc-sidebar a {',
'  display: block;',
'  margin: 0.3rem 0;',
'  color: var(--text-dark);',
'  text-decoration: none;',
'}',
'.doc-sidebar a:hover { text-decoration: underline; color: var(--primary-color); }',
'',
'/* Responsive */',
'@media(max-width:768px){',
'  .main-wrapper {',
'    flex-direction: column;',
'  }',
'  .right-column { width: 100%; position: static; top: auto; margin-top: 2rem; }',
'}',
'',
'',
'/* Instructions Section */',
'.instructions {',
'  background: #fff;',
'  padding: 2rem;',
'  margin: 2rem 0;',
'  border-radius: 12px;',
'  box-shadow: 0 4px 10px rgba(0,0,0,0.1);',
'}',
'',
'.instructions h2 {',
'  margin-bottom: 1rem;',
'  color: var(--primary-color);',
'}',
'',
'.instructions ul {',
'  list-style: none;',
'  padding: 0;',
'}',
'',
'.instructions li {',
'  margin-bottom: 1rem;',
'  font-size: 1.1rem;',
'}',
'',
'.instructions a {',
'  color: var(--text-dark);',
'  font-weight: bold;',
'  text-decoration: none;',
'}',
'',
'.instructions a:hover {',
'  color: var(--primary-color);',
'}',
'',
'.instructions .note {',
'  font-size: 0.9rem;',
'  color: #666;',
'  margin-left: 1.2rem;',
'}',
'/* CTA Section */',
'.cta-section {',
'  background: var(--primary-color);',
'  text-align: center;',
'  padding: 3rem 2rem;',
'  margin: 3rem 0 0;',
'  border-radius: 12px 12px 0 0;',
'  color: #000;',
'}',
'',
'.cta-section h2 {',
'  font-size: 2rem;',
'  margin-bottom: 1rem;',
'}',
'',
'.cta-section p {',
'  font-size: 1.2rem;',
'  margin-bottom: 2rem;',
'}',
'',
'.cta-btn {',
'  display: inline-block;',
'  background: #000;',
'  color: #fff;',
'  padding: 0.8rem 2rem;',
'  border-radius: 8px;',
'  font-size: 1.2rem;',
'  font-weight: bold;',
'  text-decoration: none;',
'  transition: background 0.3s;',
'}',
'',
'.cta-btn:hover {',
'  background: #333;',
'}',
''))
,p_step_template=>2979075366320325194
,p_page_template_options=>'#DEFAULT#'
,p_page_is_public_y_n=>'Y'
,p_page_component_map=>'11'
);
wwv_flow_imp_page.create_page_plug(
 p_id=>wwv_flow_imp.id(1657173607487213)
,p_plug_name=>'html'
,p_region_template_options=>'#DEFAULT#'
,p_plug_template=>3371237801798025892
,p_plug_display_sequence=>10
,p_location=>null
,p_plug_source=>wwv_flow_string.join(wwv_flow_t_varchar2(
'<header>Employee Management Module</header>',
'',
'<div class="main-wrapper">',
'    <!-- Left Column -->',
'    <div class="left-column">',
'        <!-- Top Cards Section -->',
'        <div class="top-cards">',
'            <div class="card">',
'            <h2>Employee Report</h2>',
'            <p>View all employees, search, filter, and manage records.</p>',
'            <a href="https://mesbahuddin.com/web/r/apps/playground/report-dashboard" class="btn" target="_blank">Go to Report</a>',
'            </div>',
'',
'            <div class="card">',
'            <h2>Add / Edit Employee</h2>',
'            <p>Register new employees or update existing employee information.</p>',
'            <a href="https://mesbahuddin.com/web/r/apps/playground/employee-entry" class="btn" target="_blank">Go to Entry</a>',
'            </div>',
'',
'            <div class="card">',
'            <h2>Employee Resume</h2>',
'            <p>Generate and view printable CVs with export option.</p>',
'            <button type="button"class="btn" id="resumeBtn">View Resume</button>',
'            </div>',
'',
'        </div>',
'',
'',
'    <!-- Instruction Section -->',
'    <div class="instructions">',
unistr('    <h2>\D83D\DCCC How to Explore the Project</h2>'),
'    <p>Please follow the links below to view and test the project resources:</p>',
'',
'    <ul>',
'        <li>',
unistr('        \25B6\FE0F <strong>Project Demo:</strong>  '),
'        <a href="https://mesbahuddin.com/web/r/apps/playground/report-dashboard" target="_blank">',
'            View Project in Action',
'        </a>',
'        </li>',
'        <li>',
unistr('        \D83D\DCC2 <strong>Full Documentation & Source Code:</strong>  '),
'        <a href="https://github.com/mesbahworld/Employee-Entry-CV-Generator" target="_blank">',
'            GitHub Repository',
'        </a>  ',
'        <p class="note">Includes APEX pages, static files, DB objects (tables, views, packages, functions, procedures, triggers, indexes) and demo insert data script.</p>',
'        </li>',
'        <li>',
unistr('        \D83D\DD17 <strong>API Explorer:</strong>  '),
'        <a href="https://mesbahuddin.com/playground/api" target="_blank">',
'            Open API Documentation & Testing',
'        </a>',
'        </li>',
'    </ul>',
'    </div>',
'',
'',
'',
'        <!-- Documentation Section -->',
'        <div class="docs-section" id="docsSection">',
'        <div class="doc-card" id="doc1">',
'            <h3>Employee Table Schema</h3>',
'            <a href="#doc1" class="doc-id-link">#doc1</a>',
'            <p>Description: All the tables that used in this task!</p>',
'            <div class="doc-tag">SQL</div>',
'            <pre><code class="language-sql">',
'-- =============================================',
'-- Employee Management System - Task Compliant Schema with PG1_ Prefix (PlayGround 1)',
'-- Tables: PG1_EMPLOYEE_MASTER, PG1_EMPLOYEE_EDUCATION, PG1_EMPLOYEE_EXPERIENCE, PG1_LOOKUP_VALUES, PG1_DEPARTMENT_MASTER, PG1_DESIGNATION_MASTER',
'-- =============================================',
'',
'-- 1. PG1_EMPLOYEE_MASTER Table',
'-- =============================================',
'',
'CREATE TABLE PG1_EMPLOYEE_MASTER (',
'    EMP_ID NUMBER PRIMARY KEY,',
'    EMP_CODE VARCHAR2(20) UNIQUE NOT NULL,',
'    FIRST_NAME VARCHAR2(50) NOT NULL,',
'    LAST_NAME VARCHAR2(50) NOT NULL,',
'    FULL_NAME VARCHAR2(101) GENERATED ALWAYS AS (FIRST_NAME || '' '' || LAST_NAME) VIRTUAL,',
'    EMAIL VARCHAR2(100) UNIQUE NOT NULL,',
'    PHONE VARCHAR2(20),',
'    MOBILE VARCHAR2(20),',
'    NID VARCHAR2(17) UNIQUE NOT NULL,',
'    DATE_OF_BIRTH DATE,',
'    ',
'    -- Dynamic dropdown fields (from database, not static)',
'    GENDER VARCHAR2(20), -- Will be populated from lookup',
'    BLOOD_GROUP VARCHAR2(10), -- Will be populated from lookup  ',
'    RELIGION VARCHAR2(50), -- Will be populated from lookup',
'    ',
'    -- Searchable dropdown fields - storing both ID and name for performance',
'    DEPARTMENT_ID NUMBER,',
'    DEPARTMENT_NAME VARCHAR2(100), -- Denormalized for faster queries ',
'    DESIGNATION_ID NUMBER,',
'    DESIGNATION_NAME VARCHAR2(100), -- Denormalized for faster queries',
'    ',
'    JOIN_DATE DATE DEFAULT SYSDATE,',
'    SALARY NUMBER(12,2),',
'    ADDRESS_PRESENT VARCHAR2(500),',
'    ADDRESS_PERMANENT VARCHAR2(500),',
'    EMERGENCY_CONTACT_NAME VARCHAR2(100),',
'    EMERGENCY_CONTACT_PHONE VARCHAR2(20),',
'    MARITAL_STATUS VARCHAR2(20) CHECK (MARITAL_STATUS IN (''Single'', ''Married'', ''Divorced'', ''Widowed'')),',
'    ',
'    -- Enhanced fields for advanced features',
'    SKILLS VARCHAR2(4000), -- JSON format for skills array',
'    PHOTO BLOB,',
'    PHOTO_FILENAME VARCHAR2(255),',
'    PHOTO_MIME_TYPE VARCHAR2(100),',
'    ',
'    -- System fields',
'    IS_ACTIVE CHAR(1) DEFAULT ''Y'' CHECK (IS_ACTIVE IN (''Y'', ''N'')),',
'    CREATED_DATE DATE DEFAULT SYSDATE,',
'    CREATED_BY VARCHAR2(100) DEFAULT USER,',
'    MODIFIED_DATE DATE,',
'    MODIFIED_BY VARCHAR2(100),',
'    ',
'    -- Validation constraints',
'    CONSTRAINT PG1_CHK_EMAIL_FORMAT CHECK (REGEXP_LIKE(EMAIL, ''^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'')),',
'    CONSTRAINT PG1_CHK_NID_FORMAT CHECK (REGEXP_LIKE(NID, ''^[0-9]{10}$|^[0-9]{13}$|^[0-9]{17}$''))',
');',
'',
'-- 2. PG1_EMPLOYEE_EDUCATION Table ',
'-- =============================================',
'',
'CREATE TABLE PG1_EMPLOYEE_EDUCATION (',
'    EDU_ID NUMBER PRIMARY KEY,',
'    EMP_ID NUMBER NOT NULL,',
'    DEGREE_TYPE VARCHAR2(50) NOT NULL, -- SSC, HSC, Bachelor, Master, PhD, Diploma, etc.',
'    DEGREE_TITLE VARCHAR2(100) NOT NULL, -- Computer Science, Business Administration, etc.',
'    INSTITUTION_NAME VARCHAR2(200) NOT NULL,',
'    PASSING_YEAR NUMBER(4) NOT NULL,',
'    RESULT_TYPE VARCHAR2(20), -- GPA, CGPA, Division, Grade, Percentage',
'    RESULT_VALUE VARCHAR2(20), -- 3.75, First Division, A+, 85%, etc.',
'    DURATION_YEARS NUMBER(2), -- Duration in years',
'    MAJOR_SUBJECT VARCHAR2(100), -- Major/Concentration',
'    IS_CURRENT CHAR(1) DEFAULT ''N'' CHECK (IS_CURRENT IN (''Y'', ''N'')),',
'    ',
'    -- System fields',
'    CREATED_DATE DATE DEFAULT SYSDATE,',
'    CREATED_BY VARCHAR2(100) DEFAULT USER,',
'    MODIFIED_DATE DATE,',
'    MODIFIED_BY VARCHAR2(100),',
'    ',
'    -- Foreign key constraint',
'    CONSTRAINT PG1_FK_EDU_EMP FOREIGN KEY (EMP_ID) REFERENCES PG1_EMPLOYEE_MASTER(EMP_ID) ON DELETE CASCADE,',
'    CONSTRAINT PG1_CHK_PASSING_YEAR CHECK (PASSING_YEAR BETWEEN 1950 AND 2030)',
');',
'',
'-- 3. PG1_EMPLOYEE_EXPERIENCE Table ',
'-- =============================================',
'',
'CREATE TABLE PG1_EMPLOYEE_EXPERIENCE (',
'    EXP_ID NUMBER PRIMARY KEY,',
'    EMP_ID NUMBER NOT NULL,',
'    COMPANY_NAME VARCHAR2(200) NOT NULL,',
'    DESIGNATION VARCHAR2(100) NOT NULL,',
'    DEPARTMENT VARCHAR2(100),',
'    START_DATE DATE NOT NULL,',
'    END_DATE DATE,',
'    IS_CURRENT CHAR(1) DEFAULT ''N'' CHECK (IS_CURRENT IN (''Y'', ''N'')),',
'    JOB_RESPONSIBILITIES CLOB,',
'    SALARY_RANGE VARCHAR2(50), -- 50000-70000, 1.5L-2L, etc.',
'    REASON_FOR_LEAVING VARCHAR2(200),',
'    SUPERVISOR_NAME VARCHAR2(100),',
'    SUPERVISOR_CONTACT VARCHAR2(50),',
'    ',
'    -- Enhanced fields',
'    LOCATION VARCHAR2(100), -- Work location',
'    EMPLOYMENT_TYPE VARCHAR2(30), -- Full-time, Part-time, Contract, Internship',
'    ',
'    -- System fields',
'    CREATED_DATE DATE DEFAULT SYSDATE,',
'    CREATED_BY VARCHAR2(100) DEFAULT USER,',
'    MODIFIED_DATE DATE,',
'    MODIFIED_BY VARCHAR2(100),',
'    ',
'    -- Foreign key constraint',
'    CONSTRAINT PG1_FK_EXP_EMP FOREIGN KEY (EMP_ID) REFERENCES PG1_EMPLOYEE_MASTER(EMP_ID) ON DELETE CASCADE,',
'    CONSTRAINT PG1_CHK_DATE_LOGIC CHECK (END_DATE IS NULL OR END_DATE >= START_DATE)',
');',
'',
'-- 4. Supporting Lookup Tables',
'-- =============================================',
'',
'-- Simple lookup table for dynamic dropdowns',
'CREATE TABLE PG1_LOOKUP_VALUES (',
'    LOOKUP_ID NUMBER PRIMARY KEY,',
'    LOOKUP_TYPE VARCHAR2(50) NOT NULL, -- GENDER, BLOOD_GROUP, RELIGION',
'    LOOKUP_CODE VARCHAR2(20) NOT NULL,',
'    LOOKUP_VALUE VARCHAR2(100) NOT NULL,',
'    DISPLAY_ORDER NUMBER DEFAULT 0,',
'    IS_ACTIVE CHAR(1) DEFAULT ''Y'' CHECK (IS_ACTIVE IN (''Y'', ''N'')),',
'    CREATED_DATE DATE DEFAULT SYSDATE,',
'    CONSTRAINT PG1_UK_LOOKUP_TYPE_CODE UNIQUE (LOOKUP_TYPE, LOOKUP_CODE)',
');',
'',
'-- Department master for searchable dropdown',
'CREATE TABLE PG1_DEPARTMENT_MASTER (',
'    DEPT_ID NUMBER PRIMARY KEY,',
'    DEPT_CODE VARCHAR2(20) UNIQUE NOT NULL,',
'    DEPT_NAME VARCHAR2(100) NOT NULL,',
'    DEPT_HEAD VARCHAR2(100),',
'    IS_ACTIVE CHAR(1) DEFAULT ''Y'' CHECK (IS_ACTIVE IN (''Y'', ''N'')),',
'    CREATED_DATE DATE DEFAULT SYSDATE',
');',
'',
'-- Designation master for searchable dropdown',
'CREATE TABLE PG1_DESIGNATION_MASTER (',
'    DESIG_ID NUMBER PRIMARY KEY,',
'    DESIG_CODE VARCHAR2(20) UNIQUE NOT NULL,',
'    DESIG_NAME VARCHAR2(100) NOT NULL,',
'    DEPT_ID NUMBER, -- Optional link to department',
'    IS_ACTIVE CHAR(1) DEFAULT ''Y'' CHECK (IS_ACTIVE IN (''Y'', ''N'')),',
'    CREATED_DATE DATE DEFAULT SYSDATE,',
'    CONSTRAINT PG1_FK_DESIG_DEPT FOREIGN KEY (DEPT_ID) REFERENCES PG1_DEPARTMENT_MASTER(DEPT_ID)',
');',
'',
'            </code></pre>',
'            <div class="doc-links">',
'            <a href="https://github.com/mesbahworld/Employee-Entry-CV-Generator" target="_blank">GitHub</a>',
'            <a href="https://mesbahuddin.com/web/r/apps/playground/employee-entry" target="_blank">APEX Entry Page</a>',
'            </div>',
'        </div>',
'',
'        <div class="doc-card" id="doc2">',
'            <h3>Employee API Example</h3>',
'            <a href="#doc2" class="doc-id-link">#doc2</a>',
'            <p>Description: This is just one example of api</p>',
'            <p>Insert Data from custom form to database using post API with json payload</p>',
'            <div class="doc-tag">JavaScript</div><div class="doc-tag">REST API</div><div class="doc-tag">ORDS</div><div class="doc-tag">curl</div>',
'            <pre><code class="language-curl">',
'curl --location ''https://mesbahuddin.com/web/unorg/pg1_emp_man/data'' \',
'--header ''Content-Type: application/json'' \',
'--data-raw ''{',
'  "emp_id": null,',
'  "first_name": "John",',
'  "last_name": "Doe",',
'  "email": "john.doe@updated.com",',
'  "phone": "1234567890",',
'  "mobile": "9876543210",',
'  "nid": "1234567890123",',
'  "date_of_birth": "1990-01-01",',
'  "gender": "M",',
'  "blood_group": "O+",',
'  "religion": "Islam",',
'  "department_id": 1,',
'  "designation_id": 2,',
'  "join_date": "2020-01-01",',
'  "salary": 50000,',
'  "address_present": "Dhaka",',
'  "address_permanent": "Chittagong",',
'  "emergency_contact_name": "Jane Doe",',
'  "emergency_contact_phone": "0123456789",',
'  "marital_status": "Married",',
'  "skills": "Oracle, PL/SQL, APEX",',
'',
'  "education": [',
'    {',
'      "degree_type": "BSc",',
'      "degree_title": "Computer Science",',
'      "institution_name": "Dhaka University",',
'      "passing_year": 2012,',
'      "result_type": "CGPA",',
'      "result_value": "3.8",',
'      "duration_years": 4,',
'      "major_subject": "CSE",',
'      "is_current": "N"',
'    },',
'    {',
'      "degree_type": "MSc",',
'      "degree_title": "Software Engineering",',
'      "institution_name": "BUET",',
'      "passing_year": 2014,',
'      "result_type": "CGPA",',
'      "result_value": "3.9",',
'      "duration_years": 2,',
'      "major_subject": "SE",',
'      "is_current": "N"',
'    }',
'  ],',
'',
'  "experience": [',
'    {',
'      "company_name": "ABC Ltd",',
'      "designation": "Software Engineer",',
'      "department": "IT",',
'      "start_date": "2015-01-01",',
'      "end_date": "2018-01-01",',
'      "is_current": "N",',
'      "jobResponsibilities": "-Developed responsive web applications for international clients using HTML5, CSS3, and JavaScript\n-Created user-centered interfaces improving conversion rates by 40%\n-Implemented front-end solutions with focus on user'
||' experience and accessibility\n-Gained experience in full project lifecycle from requirements to deployment",',
'      "salary_range": "30k-40k",',
'      "reason_for_leaving": "Better opportunity",',
'      "supervisor_name": "Mr. X",',
'      "supervisor_contact": "0123456789",',
'      "location": "Dhaka",',
'      "employment_type": "Full-time"',
'    },',
'    {',
'      "company_name": "XYZ Ltd",',
'      "designation": "Senior Software Engineer",',
'      "department": "IT",',
'      "start_date": "2018-02-01",',
'      "end_date": null,',
'      "is_current": "Y",',
'      "jobResponsibilities": "-Led development team of 4 developers for parcel management system handling 10,000+ daily transactions\n-Designed and implemented REST APIs for mobile and web clients using ORDS\n-Developed complex Oracle APEX reports an'
||'d dashboards for business analytics\n-Optimized PL/SQL routines improving system performance by 35%\n-Implemented automated data validation processes reducing errors by 40%\n-Architected high-performance logistics tracking system with real-time updat'
||'es\n-Created automated reporting solutions reducing manual work by 80%\n-Managed database administration tasks including backup, recovery, and performance tuning",',
'      "salary_range": "50k-60k",',
'      "reason_for_leaving": null,',
'      "supervisor_name": "Mr. Y",',
'      "supervisor_contact": "0987654321",',
'      "location": "Chittagong",',
'      "employment_type": "Full-time"',
'    }',
'  ]',
'}',
'',
'            </code></pre>',
'<h3>response example:</h3>',
'',
'            <pre><code class="language-json">',
'{',
'    "status": "success",',
'    "statusCode": 200,',
'    "emp_id": 11,',
'    "message": "Employee saved successfully"',
'}',
'            </code></pre>',
'',
'            <pre><code class="language-json">',
'{',
'    "status": "error",',
'    "statusCode": 404,',
'    "message": "Employee not found / Random error"',
'}',
'',
'          ',
'            </code></pre>',
'',
'',
'            <div class="doc-links">',
'            <a href="https://mesbahuddin.com/playground/api" target="_blank">API Link</a>',
'            </div>',
'        </div>',
'        </div>',
'    </div>',
'',
'',
'',
'',
'    <!-- Right Column (Floating Sidebar) -->',
'    <div class="right-column">',
'        <div class="doc-sidebar" id="docSidebar">',
'        <h4>Documentation</h4>',
'        <!-- Links populated dynamically -->',
'        </div>',
'    </div>',
'</div>',
'',
'<!-- Call to Action Section -->',
'<div class="cta-section">',
unistr('  <h2>\D83D\DE80 Explore the Full Project Documentation</h2>'),
'  <p>Download APEX pages, static files, database objects, and scripts directly from GitHub.</p>',
'  <a href="https://github.com/mesbahworld/Employee-Entry-CV-Generator" target="_blank" class="cta-btn">',
'    Visit GitHub Repository',
'  </a>',
'</div>',
'',
'',
'',
'<!-- Resume Modal -->',
'<div class="modal" id="resumeModal">',
'  <div class="modal-content">',
'    <span class="close-btn" id="closeModal">&times;</span>',
'    <h3>Search Employee</h3>',
'    <input type="text" id="empSearch" placeholder="Enter name or ID">',
'    <div class="search-result" id="searchResults"></div>',
'  </div>',
'</div>',
''))
,p_attributes=>wwv_flow_t_plugin_attributes(wwv_flow_t_varchar2(
  'expand_shortcuts', 'N',
  'output_as', 'HTML')).to_clob
);
wwv_flow_imp_page.create_page_plug(
 p_id=>wwv_flow_imp.id(1657340997487215)
,p_plug_name=>'main-wrapper'
,p_region_css_classes=>'main-wrapper'
,p_region_template_options=>'#DEFAULT#:t-Region--scrollBody'
,p_plug_template=>4072358936313175081
,p_plug_display_sequence=>30
,p_location=>null
,p_plug_source=>'<header>Employee Management Module</header>'
,p_required_patch=>wwv_flow_imp.id(1983389970145504)
,p_attributes=>wwv_flow_t_plugin_attributes(wwv_flow_t_varchar2(
  'expand_shortcuts', 'N',
  'output_as', 'HTML')).to_clob
);
end;
/
prompt --application/end_environment
begin
wwv_flow_imp.import_end(p_auto_install_sup_obj => nvl(wwv_flow_application_install.get_auto_install_sup_obj, false)
);
commit;
end;
/
set verify on feedback on define on
prompt  ...done
