prompt --application/set_environment
set define off verify off feedback off
whenever sqlerror exit sql.sqlcode rollback
--------------------------------------------------------------------------------
--
-- Oracle APEX export file
--
-- You should run this script using a SQL client connected to the database as
-- the owner (parsing schema) of the application or as a database user with the
-- APEX_ADMINISTRATOR_ROLE role.
--
-- This export file has been automatically generated. Modifying this file is not
-- supported by Oracle and can lead to unexpected application and/or instance
-- behavior now or in the future.
--
-- NOTE: Calls to apex_application_install override the defaults below.
--
--------------------------------------------------------------------------------
begin
wwv_flow_imp.import_begin (
 p_version_yyyy_mm_dd=>'2024.11.30'
,p_release=>'24.2.0'
,p_default_workspace_id=>100000
,p_default_application_id=>135
,p_default_id_offset=>0
,p_default_owner=>'UNORGANIZED'
);
end;
/
 
prompt APPLICATION 135 - Playground
--
-- Application Export:
--   Application:     135
--   Name:            Playground
--   Exported By:     MESBAHWORLD
--   Flashback:       0
--   Export Type:     Page Export
--   Manifest
--     PAGE: 3
--   Manifest End
--   Version:         24.2.0
--   Instance ID:     743399910586821
--

begin
null;
end;
/
prompt --application/pages/delete_00003
begin
wwv_flow_imp_page.remove_page (p_flow_id=>wwv_flow.g_flow_id, p_page_id=>3);
end;
/
prompt --application/pages/page_00003
begin
wwv_flow_imp_page.create_page(
 p_id=>3
,p_name=>'Employee Entry'
,p_alias=>'EMPLOYEE-ENTRY'
,p_step_title=>'Employee Entry'
,p_autocomplete_on_off=>'OFF'
,p_javascript_file_urls=>'#APP_FILES#js/page3custom#MIN#.js'
,p_css_file_urls=>wwv_flow_string.join(wwv_flow_t_varchar2(
'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css',
'#APP_FILES#css/page3custom#MIN#.css'))
,p_inline_css=>wwv_flow_string.join(wwv_flow_t_varchar2(
'        :root {',
'            --primary-color: #FFD700;',
'            --secondary-color: #333;',
'            --light-gray: #f5f5f5;',
'            --border-color: #ddd;',
'            --shadow: 0 4px 6px rgba(0, 0, 0, 0.1);',
'            --transition: all 0.3s ease;',
'        }',
'        ',
'        * {',
'            margin: 0;',
'            padding: 0;',
'            box-sizing: border-box;',
'            font-family: ''Segoe UI'', Tahoma, Geneva, Verdana, sans-serif;',
'        }',
'',
'        .t-Footer, .t-Header  {',
'            display: none !important;',
'        }',
'',
'        .sticky-actions {',
'            position: fixed;',
'            bottom: 0;',
'            left: 0;',
'            right: 0;',
'            background: white;',
'            padding: 5px 50px;',
'            box-shadow: 0 -4px 10px rgba(0, 0, 0, 0.1);',
'            z-index: 1000;',
'            display: flex;',
'            justify-content: flex-end;',
'            gap: 15px;',
'            justify-content: center;',
'        }',
'',
'        /* Add padding to body to prevent content from being hidden behind sticky buttons */',
'        body {',
'            padding-bottom: 80px;',
'        }',
'',
'        /* Responsive adjustments for sticky buttons */',
'        @media (max-width: 768px) {',
'            .sticky-actions {',
'                flex-direction: row;',
'                padding: 10px 15px;',
'            }',
'            ',
'            .sticky-actions .btn {',
'                width: 100%;',
'                margin-bottom: 0px;',
'            }',
'            ',
'            body {',
'                padding-bottom: 150px; /* Adjust based on button height */',
'            }',
'        }',
'        ',
'        body {',
'            background-color: #f9f9f9;',
'            color: #333;',
'            line-height: 1.6;',
'            padding: 20px;',
'        }',
'        ',
'        .container {',
'            max-width: 1200px;',
'            margin: 0 auto;',
'        }',
'        ',
'        .header {',
'            text-align: center;',
'            margin-bottom: 30px;',
'            padding: 20px;',
'            background: linear-gradient(135deg, #fff 0%, var(--primary-color) 100%);',
'            border-radius: 8px;',
'            box-shadow: var(--shadow);',
'        }',
'        ',
'        .header h1 {',
'            color: var(--secondary-color);',
'            font-size: 2.5rem;',
'            margin-bottom: 10px;',
'        }',
'        ',
'        .header p {',
'            color: #666;',
'            font-size: 1.1rem;',
'        }',
'        ',
'        .card {',
'            background: white;',
'            border-radius: 8px;',
'            box-shadow: var(--shadow);',
'            margin-bottom: 25px;',
'            overflow: hidden;',
'        }',
'        ',
'        .card-header {',
'            background-color: var(--primary-color);',
'            padding: 15px 20px;',
'            color: var(--secondary-color);',
'            font-weight: bold;',
'            font-size: 1.2rem;',
'            display: flex;',
'            justify-content: space-between;',
'            align-items: center;',
'        }',
'        ',
'        .card-body {',
'            padding: 20px;',
'        }',
'        ',
'        label {',
'            display: block;',
'            margin-bottom: 5px;',
'            font-weight: 600;',
'            color: #555;',
'        }',
'',
'        .form-control {',
'            width: 100%;',
'            padding: 12px;',
'            border: 1px solid var(--border-color);',
'            border-radius: 4px;',
'            font-size: 1rem;',
'            transition: var(--transition);',
'        }',
'        ',
'        .form-control:focus {',
'            outline: none;',
'            border-color: var(--primary-color);',
'            box-shadow: 0 0 0 3px rgba(255, 215, 0, 0.2);',
'        }',
'        ',
'        .btn {',
'            padding: 12px 20px;',
'            border: none;',
'            border-radius: 4px;',
'            cursor: pointer;',
'            font-size: 1rem;',
'            font-weight: 600;',
'            transition: var(--transition);',
'            display: inline-flex;',
'            align-items: center;',
'            justify-content: center;',
'        }',
'        ',
'        .btn-primary {',
'            background-color: var(--primary-color);',
'            color: var(--secondary-color);',
'        }',
'        ',
'        .btn-primary:hover {',
'            background-color: #e6c300;',
'        }',
'        ',
'        .btn-danger {',
'            background-color: #dc3545;',
'            color: white;',
'        }',
'        ',
'        .btn-danger:hover {',
'            background-color: #c82333;',
'        }',
'        ',
'        .btn-success {',
'            background-color: #28a745;',
'            color: white;',
'        }',
'        ',
'        .btn-success:hover {',
'            background-color: #218838;',
'        }',
'        ',
'        .btn-info {',
'            background-color: #17a2b8;',
'            color: white;',
'        }',
'        ',
'        .btn-info:hover {',
'            background-color: #138496;',
'        }',
'        ',
'        .btn-warning {',
'            background-color: #ffc107;',
'            color: var(--secondary-color);',
'        }',
'        ',
'        .btn-warning:hover {',
'            background-color: #e0a800;',
'        }',
'        ',
'        .btn i {',
'            margin-right: 8px;',
'        }',
'        ',
'        .dynamic-row {',
'            background-color: var(--light-gray);',
'            padding: 15px;',
'            border-radius: 4px;',
'            margin-bottom: 15px;',
'            position: relative;',
'        }',
'        ',
'        .remove-row {',
'            position: absolute;',
'            top: 10px;',
'            right: 10px;',
'            color: #dc3545;',
'            cursor: pointer;',
'            font-size: 1.2rem;',
'        }',
'        ',
'        .section-title {',
'            border-bottom: 2px solid var(--primary-color);',
'            padding-bottom: 10px;',
'            margin-bottom: 20px;',
'            color: var(--secondary-color);',
'        }',
'        ',
'/*         .actions {',
'            display: flex;',
'            justify-content: flex-end;',
'            gap: 5px;',
'            margin-top: 5px;',
'        } */',
'        ',
'        /* Responsive adjustments */',
'        @media (max-width: 768px) {',
'            .ui-row {',
'                flex-direction: row !important;',
'            }',
'            ',
'            .ui-col-1, .ui-col-2, .ui-col-3, .ui-col-4, .ui-col-5, .ui-col-6,',
'            .ui-col-7, .ui-col-8, .ui-col-9, .ui-col-10, .ui-col-11, .ui-col-12 {',
'                flex: 0 0 100%;',
'                max-width: 100%;',
'            }',
'            ',
'            .header h1 {',
'                font-size: 2rem;',
'            }',
'            ',
'            .btn {',
'                width: 100%;',
'                margin-bottom: 10px;',
'                margin-left: 0px !important;',
'            }',
'            ',
'/*             .actions {',
'                flex-direction: column;',
'            } */',
'        }',
'',
'        /* Grid System */',
'',
'',
'/*         .ui-row {',
'            display: flex;',
'            flex-wrap: wrap;',
'            margin: -10px;',
'        }',
'        ',
'        .ui-col {',
'            padding: 10px;',
'            flex: 1;',
'        }',
'        ',
'        .ui-col-1 { flex: 0 0 8.333333%; max-width: 8.333333%; }',
'        .ui-col-2 { flex: 0 0 16.666667%; max-width: 16.666667%; }',
'        .ui-col-3 { flex: 0 0 25%; max-width: 25%; }',
'        .ui-col-4 { flex: 0 0 33.333333%; max-width: 33.333333%; }',
'        .ui-col-5 { flex: 0 0 41.666667%; max-width: 41.666667%; }',
'        .ui-col-6 { flex: 0 0 50%; max-width: 50%; }',
'        .ui-col-7 { flex: 0 0 58.333333%; max-width: 58.333333%; }',
'        .ui-col-8 { flex: 0 0 66.666667%; max-width: 66.666667%; }',
'        .ui-col-9 { flex: 0 0 75%; max-width: 75%; }',
'        .ui-col-10 { flex: 0 0 83.333333%; max-width: 83.333333%; }',
'        .ui-col-11 { flex: 0 0 91.666667%; max-width: 91.666667%; }',
'        .ui-col-12 { flex: 0 0 100%; max-width: 100%; }',
' */',
'        .form-group {',
'            margin-bottom: 15px;',
'        }',
'        ',
'        /* Custom checkbox and radio */',
'        .checkbox-group, .radio-group {',
'            display: flex;',
'            flex-wrap: wrap;',
'            gap: 15px;',
'            margin-top: 5px;',
'        }',
'        ',
'        .checkbox-group label, .radio-group label {',
'            display: flex;',
'            align-items: center;',
'            font-weight: normal;',
'            cursor: pointer;',
'        }',
'        ',
'        .checkbox-group input, .radio-group input {',
'            margin-right: 8px;',
'        }',
'        ',
'        /* Form validation styles */',
'        .error {',
'            color: #dc3545;',
'            font-size: 0.9rem;',
'            margin-top: 5px;',
'            display: none;',
'        }',
'        ',
'        .form-control.error-field {',
'            border-color: #dc3545;',
'        }',
'        ',
'        /* Photo upload preview */',
'        .photo-upload {',
'            display: flex;',
'            flex-direction: column;',
'            align-items: center;',
'        }',
'        ',
'        .photo-preview {',
'            width: 150px;',
'            height: 150px;',
'            border: 2px dashed var(--border-color);',
'            border-radius: 50%;',
'            display: flex;',
'            align-items: center;',
'            justify-content: center;',
'            margin-bottom: 15px;',
'            overflow: hidden;',
'            background-color: var(--light-gray);',
'        }',
'        ',
'        .photo-preview img {',
'            max-width: 100%;',
'            max-height: 100%;',
'            display: none;',
'        }',
'        ',
'        /* Tabs for sections */',
'        .tabs {',
'            display: flex;',
'            margin-bottom: 20px;',
'            overflow-x: auto;',
'        }',
'        ',
'        .tab {',
'            padding: 12px 25px;',
'            background-color: #eee;',
'            cursor: pointer;',
'            border-radius: 4px 4px 0 0;',
'            margin-right: 5px;',
'            font-weight: 600;',
'        }',
'        ',
'        .tab.active {',
'            background-color: var(--primary-color);',
'            color: var(--secondary-color);',
'        }',
'        ',
'        .tab-content {',
'            display: none;',
'        }',
'        ',
'        .tab-content.active {',
'            display: block;',
'        }',
'        ',
'        /* Status messages */',
'        .status-message {',
'            padding: 15px;',
'            margin: 20px 0;',
'            border-radius: 4px;',
'            display: none;',
'        }',
'        ',
'        .status-success {',
'            background-color: #d4edda;',
'            color: #155724;',
'            border: 1px solid #c3e6cb;',
'        }',
'        ',
'        .status-error {',
'            background-color: #f8d7da;',
'            color: #721c24;',
'            border: 1px solid #f5c6cb;',
'        }',
'        ',
'        .status-warning {',
'            background-color: #fff3cd;',
'            color: #856404;',
'            border: 1px solid #ffeaa7;',
'        }',
'        ',
'        /* Floating notification */',
'        .floating-notification {',
'            position: fixed;',
'            top: 20px;',
'            right: 20px;',
'            min-width: 300px;',
'            max-width: 400px;',
'            padding: 15px 20px;',
'            border-radius: 8px;',
'            box-shadow: 0 8px 16px rgba(0, 0, 0, 0.2);',
'            z-index: 10000;',
'            transform: translateX(400px);',
'            opacity: 0;',
'            transition: all 0.3s ease;',
'            display: flex;',
'            align-items: center;',
'            gap: 10px;',
'        }',
'        ',
'        .floating-notification.show {',
'            transform: translateX(0);',
'            opacity: 1;',
'        }',
'        ',
'        .floating-notification.success {',
'            background: linear-gradient(135deg, #28a745, #20c997);',
'            color: white;',
'        }',
'        ',
'        .floating-notification.error {',
'            background: linear-gradient(135deg, #dc3545, #e74c3c);',
'            color: white;',
'        }',
'        ',
'        .floating-notification.warning {',
'            background: linear-gradient(135deg, #ffc107, #fd7e14);',
'            color: #333;',
'        }',
'        ',
'        .floating-notification .icon {',
'            font-size: 1.5rem;',
'            flex-shrink: 0;',
'        }',
'        ',
'        .floating-notification .content {',
'            flex: 1;',
'        }',
'        ',
'        .floating-notification .title {',
'            font-weight: bold;',
'            margin-bottom: 2px;',
'        }',
'        ',
'        .floating-notification .message {',
'            font-size: 0.9rem;',
'        }',
'        ',
'        .loading {',
'            display: none;',
'            text-align: center;',
'            padding: 20px;',
'        }',
'        ',
'        .loading-spinner {',
'            border: 4px solid #f3f3f3;',
'            border-top: 4px solid var(--primary-color);',
'            border-radius: 50%;',
'            width: 40px;',
'            height: 40px;',
'            animation: spin 1s linear infinite;',
'            margin: 0 auto;',
'        }',
'        ',
'        @keyframes spin {',
'            0% { transform: rotate(0deg); }',
'            100% { transform: rotate(360deg); }',
'        }',
'        ',
'        /* Search panel */',
'        .search-panel {',
'            background-color: white;',
'            padding: 20px;',
'            border-radius: 8px;',
'            box-shadow: var(--shadow);',
'            margin-bottom: 25px;',
'        }',
'        ',
'        .search-form {',
'            display: flex;',
'            gap: 15px;',
'            flex-wrap: wrap;',
'        }',
'        ',
'        .search-form .form-group {',
'            flex: 1;',
'            min-width: 200px;',
'            margin-bottom: 0;',
'        }',
'        ',
'        .employee-card {',
'            cursor: pointer;',
'            transition: var(--transition);',
'            margin-bottom: 15px;',
'        }',
'        ',
'        .employee-card:hover {',
'            transform: translateY(-3px);',
'            box-shadow: 0 6px 12px rgba(0, 0, 0, 0.15);',
'        }',
'        ',
'        .employee-list {',
'            max-height: 300px;',
'            overflow-y: auto;',
'            margin-top: 20px;',
'        }',
'        ',
'        .api-status {',
'            margin-top: 10px;',
'            padding: 10px;',
'            border-radius: 4px;',
'            text-align: center;',
'            display: none;',
'        }',
'        ',
'        .search-results-header {',
'            display: flex;',
'            justify-content: space-between;',
'            align-items: center;',
'            margin-bottom: 15px;',
'        }',
'        ',
'        /* Skills input styling */',
'        .skills-container {',
'            display: flex;',
'            flex-direction: column;',
'            gap: 10px;',
'        }',
'        ',
'        .skills-input-row {',
'            display: flex;',
'            gap: 10px;',
'            align-items: center;',
'        }',
'        ',
'        .skills-input {',
'            flex: 2;',
'            padding: 8px;',
'            border: 1px solid var(--border-color);',
'            border-radius: 4px;',
'        }',
'        ',
'        .skills-level {',
'            flex: 1;',
'            padding: 8px;',
'            border: 1px solid var(--border-color);',
'            border-radius: 4px;',
'        }',
'        ',
'        .skills-years {',
'            flex: 1;',
'            padding: 8px;',
'            border: 1px solid var(--border-color);',
'            border-radius: 4px;',
'        }',
'        ',
'        .skill-tag {',
'            display: inline-flex;',
'            align-items: center;',
'            background-color: var(--primary-color);',
'            color: var(--secondary-color);',
'            padding: 5px 10px;',
'            margin: 3px;',
'            border-radius: 15px;',
'            font-size: 0.85rem;',
'        }',
'        ',
'        .skill-tag .remove-skill {',
'            margin-left: 8px;',
'            cursor: pointer;',
'            color: #dc3545;',
'        }',
'        ',
'        .skills-display {',
'            display: flex;',
'            flex-wrap: wrap;',
'            gap: 5px;',
'            margin-top: 10px;',
'            padding: 10px;',
'            border: 1px solid var(--border-color);',
'            border-radius: 4px;',
'            min-height: 50px;',
'            background-color: #fafafa;',
'        }'))
,p_step_template=>2979075366320325194
,p_page_template_options=>'#DEFAULT#'
,p_page_is_public_y_n=>'Y'
,p_page_component_map=>'17'
);
wwv_flow_imp_page.create_page_plug(
 p_id=>wwv_flow_imp.id(1656344541487205)
,p_plug_name=>'html'
,p_region_name=>'content_region'
,p_region_template_options=>'#DEFAULT#'
,p_plug_template=>3371237801798025892
,p_plug_display_sequence=>20
,p_location=>null
,p_plug_source=>wwv_flow_string.join(wwv_flow_t_varchar2(
'    <style>',
'        ',
'    /* Simple modal popup */',
'.modal-overlay {',
'  display: none; ',
'  position: fixed;',
'  top: 0; left: 0;',
'  width: 100%; height: 100%;',
'  background: rgba(0,0,0,0.4);',
'  z-index: 999;',
'}',
'',
'.modal {',
'  background: #fff;',
'  border-radius: 10px;',
'  width: 400px;',
'  max-height: 70%;',
'  overflow-y: auto;',
'  padding: 20px;',
'  margin: 100px auto;',
'  box-shadow: 0 4px 12px rgba(0,0,0,0.2);',
'  position: relative;',
'}',
'',
'.modal h3 {',
'  margin-top: 0;',
'}',
'',
'.modal input {',
'  width: 100%;',
'  padding: 8px;',
'  margin-bottom: 12px;',
'  border: 1px solid #ddd;',
'  border-radius: 6px;',
'}',
'',
'.modal .list-item {',
'  padding: 8px;',
'  border-bottom: 1px solid #f0f0f0;',
'  cursor: pointer;',
'}',
'',
'.modal .list-item:hover {',
'  background: #007bff;',
'  color: #fff;',
'}',
'',
'.modal .close-btn {',
'  position: absolute;',
'  top: 10px; right: 10px;',
'  background: transparent;',
'  border: none;',
'  font-size: 18px;',
'  cursor: pointer;',
'}',
'    </style>',
'    ',
'    ',
'    <div class="container">',
'        <div class="header">',
'            <h1><i class="fas fa-user-tie"></i> Employee CV Builder</h1>',
'            <p>Create or update professional CVs for employee records</p>',
'        </div>',
'        ',
'        <!-- Search Panel -->',
'        <div class="search-panel">',
'',
'            ',
'            <h2 class="section-title">Find Employee</h2>',
'',
'',
'            <div class="search-form" id="search-form">',
'                <div class="form-group">',
'                    <label for="searchId">Employee ID</label>',
'                    <input type="number" id="searchId" class="form-control" placeholder="Enter employee ID">',
'                </div>',
'                <div class="form-group">',
'                    <label for="searchName">Employee Name</label>',
'                    <input type="text" id="searchName" class="form-control" placeholder="Enter employee name">',
'                </div>',
'                <div class="form-group" style="align-self: flex-end;">',
'                    <button type="button" class="btn btn-primary" id="searchBtn">',
'                        <i class="fas fa-search"></i> Search',
'                    </button>',
'                    <button type="button" class="btn btn-warning" id="clearSearchBtn" style="margin-left: 10px;">',
'                        <i class="fas fa-times"></i> Clear',
'                    </button>',
'                </div>',
'            </div>',
'',
'',
'            <!-- Modal Structure -->',
'            <div class="modal-overlay" id="popupLov">',
'            <div class="modal">',
'                <button class="close-btn" id="closePopup">&times;</button>',
'                <h3>Select Employee</h3>',
'                <input type="text" id="popupSearch" placeholder="Search employee...">',
'                <div id="popupList"></div>',
'            </div>',
'            </div>',
'            ',
'            <div id="apiStatus" class="api-status"></div>',
'            ',
'            <div id="searchResultsSection" style="display: none;">',
'                <div class="search-results-header">',
'                    <h3>Search Results</h3>',
'                    <button type="button" class="btn btn-warning" id="closeResultsBtn">',
'                        <i class="fas fa-times"></i> Close Results',
'                    </button>',
'                </div>',
'                <div class="employee-list" id="employeeList">',
'                    <!-- Employee search results will appear here -->',
'                </div>',
'            </div>',
'        </div>',
'        ',
'        <!-- Status messages -->',
'        <div id="statusMessage" class="status-message"></div>',
'        ',
'        <div class="tabs">',
'            <div class="tab active" data-tab="personal">Personal <!-- Details --></div>',
'            <div class="tab" data-tab="employment">Employment</div>',
'            <div class="tab" data-tab="education">Education</div>',
'            <div class="tab" data-tab="experience">Experience</div>',
'        </div>',
'        ',
'        <div id="employeeForm">',
'            <!-- Hidden field for employee ID (for updates) -->',
'            <input type="hidden" id="empId" data-name="empId" value="">',
'            ',
'            <!-- Personal Details Section -->',
'            <div class="tab-content active" id="personal-tab">',
'                <div class="card">',
'                    <div class="card-header">',
'                        <span>Personal Information</span>',
'                    </div>',
'                    <div class="card-body">',
'                        <div class="ui-row">',
'                            <div class="ui-col ui-col-6">',
'                                <div class="form-group">',
'                                    <label for="firstName">First Name *</label>',
'                                    <input type="text" id="firstName" data-name="firstName" class="form-control" required>',
'                                    <div class="error" id="firstNameError">Please enter a valid first name</div>',
'                                </div>',
'                            </div>',
'                            <div class="ui-col ui-col-6">',
'                                <div class="form-group">',
'                                    <label for="lastName">Last Name *</label>',
'                                    <input type="text" id="lastName" data-name="lastName" class="form-control" required>',
'                                    <div class="error" id="lastNameError">Please enter a valid last name</div>',
'                                </div>',
'                            </div>',
'                        </div>',
'                        ',
'                        <div class="ui-row">',
'                            <div class="ui-col ui-col-6">',
'                                <div class="form-group">',
'                                    <label for="email">Email Address *</label>',
'                                    <input type="email" id="email" data-name="email" class="form-control" required>',
'                                    <div class="error" id="emailError">Please enter a valid email address</div>',
'                                </div>',
'                            </div>',
'                            <div class="ui-col ui-col-6">',
'                                <div class="form-group">',
'                                    <label for="nid">National ID (NID) *</label>',
'                                    <input type="text" id="nid" data-name="nid" class="form-control" required>',
'                                    <div class="error" id="nidError">NID must be 10, 13, or 17 digits</div>',
'                                </div>',
'                            </div>',
'                        </div>',
'                        ',
'                        <div class="ui-row">',
'                            <div class="ui-col ui-col-4">',
'                                <div class="form-group">',
'                                    <label for="phone">Phone</label>',
'                                    <input type="tel" id="phone" data-name="phone" class="form-control">',
'                                </div>',
'                            </div>',
'                            <div class="ui-col ui-col-4">',
'                                <div class="form-group">',
'                                    <label for="mobile">Mobile *</label>',
'                                    <input type="tel" id="mobile" data-name="mobile" class="form-control" required>',
'                                    <div class="error" id="mobileError">Please enter a valid mobile number</div>',
'                                </div>',
'                            </div>',
'                            <div class="ui-col ui-col-4">',
'                                <div class="form-group">',
'                                    <label for="dob">Date of Birth</label>',
'                                    <input type="date" id="dob" data-name="dob" class="form-control">',
'                                </div>',
'                            </div>',
'                        </div>',
'                    </div>',
'                </div>',
'                ',
'                <div class="card">',
'                    <div class="card-header">',
'                        <span>Additional Personal Details</span>',
'                    </div>',
'                    <div class="card-body">',
'                        <div class="ui-row">',
'                            <div class="ui-col ui-col-4">',
'                                <div class="form-group">',
'                                    <label>Gender *</label>',
'                                    <select id="gender" data-name="gender" class="form-control" required>',
'                                        <option value="">Select Gender</option>',
'                                        <option value="M">Male</option>',
'                                        <option value="F">Female</option>',
'                                        <option value="O">Other</option>',
'                                    </select>',
'                                    <div class="error" id="genderError">Please select a gender</div>',
'                                </div>',
'                            </div>',
'                            <div class="ui-col ui-col-4">',
'                                <div class="form-group">',
'                                    <label>Blood Group</label>',
'                                    <select id="bloodGroup" data-name="bloodGroup" class="form-control">',
'                                        <option value="">Select Blood Group</option>',
'                                        <option value="A+">A+</option>',
'                                        <option value="A-">A-</option>',
'                                        <option value="B+">B+</option>',
'                                        <option value="B-">B-</option>',
'                                        <option value="AB+">AB+</option>',
'                                        <option value="AB-">AB-</option>',
'                                        <option value="O+">O+</option>',
'                                        <option value="O-">O-</option>',
'                                    </select>',
'                                </div>',
'                            </div>',
'                            <div class="ui-col ui-col-4">',
'                                <div class="form-group">',
'                                    <label>Religion</label>',
'                                    <select id="religion" data-name="religion" class="form-control">',
'                                        <option value="">Select Religion</option>',
'                                        <option value="ISLAM">Islam</option>',
'                                        <option value="HINDUISM">Hinduism</option>',
'                                        <option value="BUDDHISM">Buddhism</option>',
'                                        <option value="CHRISTIANITY">Christianity</option>',
'                                        <option value="OTHER">Other</option>',
'                                    </select>',
'                                </div>',
'                            </div>',
'                        </div>',
'                        ',
'                        <div class="ui-row">',
'                            <div class="ui-col ui-col-4">',
'                                <div class="form-group">',
'                                    <label>Marital Status</label>',
'                                    <div class="radio-group">',
'                                        <label><input type="radio" data-name="maritalStatus" value="Single"> Single</label>',
'                                        <label><input type="radio" data-name="maritalStatus" value="Married"> Married</label>',
'                                        <label><input type="radio" data-name="maritalStatus" value="Divorced"> Divorced</label>',
'                                        <label><input type="radio" data-name="maritalStatus" value="Widowed"> Widowed</label>',
'                                    </div>',
'                                </div>',
'                            </div>',
'                            <div class="ui-col ui-col-8">',
'                                <div class="ui-row">',
'                                    <div class="ui-col ui-col-6">',
'                                        <div class="form-group">',
'                                            <label for="emergencyContactName">Emergency Contact Name</label>',
'                                            <input type="text" id="emergencyContactName" data-name="emergencyContactName" class="form-control">',
'                                        </div>',
'                                    </div>',
'                                    <div class="ui-col ui-col-6">',
'                                        <div class="form-group">',
'                                            <label for="emergencyContactPhone">Emergency Contact Phone</label>',
'                                            <input type="text" id="emergencyContactPhone" data-name="emergencyContactPhone" class="form-control">',
'                                        </div>',
'                                    </div>',
'                                </div>',
'                            </div>',
'                        </div>',
'                    </div>',
'                </div>',
'                ',
'                <div class="card">',
'                    <div class="card-header">',
'                        <span>Address Information</span>',
'                    </div>',
'                    <div class="card-body">',
'                        <div class="form-group">',
'                            <label for="presentAddress">Present Address</label>',
'                            <textarea id="presentAddress" data-name="presentAddress" class="form-control" rows="3"></textarea>',
'                        </div>',
'                        ',
'                        <div class="form-group">',
'                            <label for="permanentAddress">Permanent Address</label>',
'                            <textarea id="permanentAddress" data-name="permanentAddress" class="form-control" rows="3"></textarea>',
'                        </div>',
'                        ',
'                        <div class="form-group">',
'                            <label class="checkbox-group">',
'                                <input type="checkbox" id="sameAsPresent"> Same as Present Address',
'                            </label>',
'                        </div>',
'                    </div>',
'                </div>',
'            </div>',
'            ',
'            <!-- Employment Section -->',
'            <div class="tab-content" id="employment-tab">',
'                <div class="card">',
'                    <div class="card-header">',
'                        <span>Employment Details</span>',
'                    </div>',
'                    <div class="card-body">',
'                        <div class="ui-row">',
'                            <div class="ui-col ui-col-6">',
'                                <div class="form-group">',
'                                    <label for="department">Department *</label>',
'                                    <select id="department" data-name="department" class="form-control" required>',
'                                        <option value="">Select Department</option>',
'                                        <!-- Departments will be loaded dynamically -->',
'                                    </select>',
'                                    <div class="error" id="departmentError">Please select a department</div>',
'                                </div>',
'                            </div>',
'                            <div class="ui-col ui-col-6">',
'                                <div class="form-group">',
'                                    <label for="designation">Designation *</label>',
'                                    <select id="designation" data-name="designation" class="form-control" required>',
'                                        <option value="">Select Designation</option>',
'                                        <!-- Designations will be loaded dynamically -->',
'                                    </select>',
'                                    <div class="error" id="designationError">Please select a designation</div>',
'                                </div>',
'                            </div>',
'                        </div>',
'                        ',
'                        <div class="ui-row">',
'                            <div class="ui-col ui-col-4">',
'                                <div class="form-group">',
'                                    <label for="joinDate">Join Date</label>',
'                                    <input type="date" id="joinDate" data-name="joinDate" class="form-control">',
'                                </div>',
'                            </div>',
'                            <div class="ui-col ui-col-4">',
'                                <div class="form-group">',
'                                    <label for="salary">Salary</label>',
'                                    <input type="number" id="salary" data-name="salary" class="form-control" step="0.01">',
'                                </div>',
'                            </div>',
'                            <div class="ui-col ui-col-4">',
'                                <div class="form-group">',
'                                    <label for="empCode">Employee Code</label>',
'                                    <input type="text" id="empCode" data-name="empCode" class="form-control" readonly>',
'                                </div>',
'                            </div>',
'                        </div>',
'                    </div>',
'                </div>',
'                ',
'                <div class="card">',
'                    <div class="card-header">',
'                        <span>Skills & Photo</span>',
'                    </div>',
'                    <div class="card-body">',
'                        <div class="ui-row">',
'                            <div class="ui-col ui-col-8">',
'                                <div class="form-group">',
'                                    <label>Skills</label>',
'                                    <div class="skills-container">',
'                                        <div class="skills-input-row">',
'                                            <input type="text" id="skillName" placeholder="Skill name" class="skills-input">',
'                                            <select id="skillLevel" class="skills-level">',
'                                                <option value="">Level</option>',
'                                                <option value="Beginner">Beginner</option>',
'                                                <option value="Intermediate">Intermediate</option>',
'                                                <option value="Advanced">Advanced</option>',
'                                                <option value="Expert">Expert</option>',
'                                            </select>',
'                                            <input type="number" id="skillYears" placeholder="Years" class="skills-years" min="0" max="50">',
'                                            <button type="button" class="btn btn-success" id="addSkillBtn">',
'                                                <i class="fas fa-plus"></i> Add',
'                                            </button>',
'                                        </div>',
'                                        <div class="skills-display" id="skillsDisplay">',
'                                            <!-- Skills will be displayed here as tags -->',
'                                        </div>',
'                                        <input type="hidden" id="skills" data-name="skills" value="">',
'                                    </div>',
'                                </div>',
'                            </div>',
'                            <div class="ui-col ui-col-4">',
'                                <div class="form-group photo-upload">',
'                                    <div class="photo-preview">',
'                                        <i class="fas fa-user fa-3x"></i>',
'                                        <img id="photoPreview" src="" alt="Photo Preview">',
'                                    </div>',
'                                    <input type="file" id="photo" data-name="photo" accept="image/*" style="display: none;">',
'                                    <button type="button" class="btn btn-primary" id="uploadBtn">',
'                                        <i class="fas fa-upload"></i> Upload Photo',
'                                    </button>',
'                                </div>',
'                            </div>',
'                        </div>',
'                    </div>',
'                </div>',
'            </div>',
'            ',
'            <!-- Education Section -->',
'            <div class="tab-content" id="education-tab">',
'                <div class="card">',
'                    <div class="card-header">',
'                        <span>Education History</span>',
'                        <button type="button" class="btn btn-success" id="addEducation">',
'                            <i class="fas fa-plus"></i> Add Education',
'                        </button>',
'                    </div>',
'                    <div class="card-body">',
'                        <div id="educationRows">',
'                            <!-- Education rows will be added here dynamically -->',
'                        </div>',
'                    </div>',
'                </div>',
'            </div>',
'            ',
'            <!-- Experience Section -->',
'            <div class="tab-content" id="experience-tab">',
'                <div class="card">',
'                    <div class="card-header">',
'                        <span>Work Experience</span>',
'                        <button type="button" class="btn btn-success" id="addExperience">',
'                            <i class="fas fa-plus"></i> Add Experience',
'                        </button>',
'                    </div>',
'                    <div class="card-body">',
'                        <div id="experienceRows">',
'                            <!-- Experience rows will be added here dynamically -->',
'                        </div>',
'                    </div>',
'                </div>',
'            </div>',
'            ',
'            <div class="loading" id="loadingIndicator">',
'                <div class="loading-spinner"></div>',
'                <p>Processing your request...</p>',
'            </div>',
'            ',
'            <div class="actions sticky-actions">',
'                <button type="button" class="btn btn-danger" id="resetForm">',
'                    <i class="fas fa-times"></i> Reset',
'                </button>',
'                <button type="button" class="btn btn-danger" id="deleteEmployee" style="display: none;">',
'                    <i class="fas fa-trash"></i> Delete',
'                </button>',
'                <button type="button" class="btn btn-primary" id="saveEmployee">',
'                    <i class="fas fa-check-circle"></i> Save',
'                </button>',
'            </div>',
'        </form>',
'    </div>',
'',
''))
,p_attributes=>wwv_flow_t_plugin_attributes(wwv_flow_t_varchar2(
  'expand_shortcuts', 'N',
  'output_as', 'HTML')).to_clob
);
wwv_flow_imp_page.create_page_item(
 p_id=>wwv_flow_imp.id(1656944827487211)
,p_name=>'P3_EMP_ID'
,p_item_sequence=>10
,p_item_plug_id=>wwv_flow_imp.id(1656344541487205)
,p_item_default=>'RETURN NULL;'
,p_item_default_type=>'FUNCTION_BODY'
,p_item_default_language=>'PLSQL'
,p_display_as=>'NATIVE_HIDDEN'
,p_attributes=>wwv_flow_t_plugin_attributes(wwv_flow_t_varchar2(
  'value_protected', 'Y')).to_clob
);
wwv_flow_imp_page.create_page_item(
 p_id=>wwv_flow_imp.id(1658386132487225)
,p_name=>'P3_DEBUG_DATA'
,p_data_type=>'CLOB'
,p_item_sequence=>30
,p_item_plug_id=>wwv_flow_imp.id(1656344541487205)
,p_display_as=>'NATIVE_HIDDEN'
,p_attributes=>wwv_flow_t_plugin_attributes(wwv_flow_t_varchar2(
  'value_protected', 'N')).to_clob
);
wwv_flow_imp_page.create_page_item(
 p_id=>wwv_flow_imp.id(1658507559487227)
,p_name=>'P3_EDIT'
,p_item_sequence=>40
,p_item_plug_id=>wwv_flow_imp.id(1656344541487205)
,p_display_as=>'NATIVE_HIDDEN'
,p_attributes=>wwv_flow_t_plugin_attributes(wwv_flow_t_varchar2(
  'value_protected', 'N')).to_clob
);
wwv_flow_imp_page.create_page_item(
 p_id=>wwv_flow_imp.id(1658604422487228)
,p_name=>'P3_MODE'
,p_item_sequence=>50
,p_item_plug_id=>wwv_flow_imp.id(1656344541487205)
,p_display_as=>'NATIVE_HIDDEN'
,p_attributes=>wwv_flow_t_plugin_attributes(wwv_flow_t_varchar2(
  'value_protected', 'N')).to_clob
);
wwv_flow_imp_page.create_page_da_event(
 p_id=>wwv_flow_imp.id(1658841444487230)
,p_name=>'clear item on page load'
,p_event_sequence=>10
,p_bind_type=>'bind'
,p_bind_event_type=>'ready'
);
wwv_flow_imp_page.create_page_da_action(
 p_id=>wwv_flow_imp.id(1658993347487231)
,p_event_id=>wwv_flow_imp.id(1658841444487230)
,p_event_result=>'TRUE'
,p_action_sequence=>10
,p_execute_on_page_init=>'Y'
,p_action=>'NATIVE_CLEAR'
,p_affected_elements_type=>'ITEM'
,p_affected_elements=>'P3_EMP_ID'
);
wwv_flow_imp_page.create_page_process(
 p_id=>wwv_flow_imp.id(1658221659487224)
,p_process_sequence=>10
,p_process_point=>'ON_DEMAND'
,p_process_type=>'NATIVE_PLSQL'
,p_process_name=>'PG1_SAVE_EMPLOYEE'
,p_process_sql_clob=>wwv_flow_string.join(wwv_flow_t_varchar2(
'DECLARE',
'v_employee_data CLOB := apex_application.g_clob_01;',
'',
'BEGIN',
'',
'',
' APEX_UTIL.SET_SESSION_STATE(''P3_DEBUG_DATA'', NVL(v_employee_data, ''No Data get''));',
'',
'    PG1_PROC_SAVE_EMPLOYEE(p_employee_data => v_employee_data);',
'END;'))
,p_process_clob_language=>'PLSQL'
,p_internal_uid=>1658221659487224
);
end;
/
prompt --application/end_environment
begin
wwv_flow_imp.import_end(p_auto_install_sup_obj => nvl(wwv_flow_application_install.get_auto_install_sup_obj, false)
);
commit;
end;
/
set verify on feedback on define on
prompt  ...done
